### PR TITLE
Add support for FreeBSD and removed xcb in favor of Xlib

### PR DESCRIPTION
**Pull request by technoprole**
I added support for FreeBSD and removed xcb depencies. 

The FreeBSD port is pretty straight forward commit.

The winpid() function did not work in my machine so I ended up removing all xcb depencies and switch (back?!?!) to Xlib. It depends on setting _NET_WM_PID on window which seems to work fine with my Xorg configuration but I don't have a clue does it get set in different flavors of linux

### CODE REVIEW

**Comment by deadpixi** [comment]
Hi @technoprole; I really appreciate the pull request.

I had had used _NET_WM_PID in earlier versions of the code, but the property is set unreliably (some software doesn't set it) or late (some software sets it after mapping), while the xcb method works around those problems. Additionally, the pid returned using the xcb method is guaranteed to be valid for the local machine (which is needed for the process tracing to work), while the _NET_WM_PID method requires checking WM_CLIENT_MACHINE and guessing on hostname and such.

So while I agree using _NET_WM_PID makes the code much cleaner and reduces dependencies, it also has some issues.

**Comment by technoprole** [comment]
I think you are right about this issue. Sorry about the noise.

**Comment by deadpixi** [comment]
@technoprole I'd still appreciate having FreeBSD support, though, if you'd be willing to submit a patch/PR for that.

**Comment by deadpixi** [comment]
Hi @technoprole 

I incorporated your FreeBSD support, and switched back to using XLib, with no xcb dependency. The FreeBSD support was copied straight from your PR, and you've been credited in the README.

The switch back to XLib was more involved, since we need to check various things to make sure _NET_WM_PID is set and valid and the right time, but that's done.

If you're still interested in the project, please feel free to test it out on your FreeBSD box.

Thanks again!

**Pull request closed without merging**
